# extensions/conflicts.conf
# format: preferred:conflict1 conflict2 ...
# when both preferred and any conflict are selected, keep preferred and remove conflict

# prefer imagick over gmagick
imagick:gmagick

# prefer opcache over apcu
opcache:apcu

# prefer mongodb over mongo
mongodb:mongo

# prefer openswoole over swoole
openswoole:swoole